// Generated by Wrangler by running `wrangler types`

interface Env {
	DB_USERNAME: "timetrap";
	DB_HOST: "dblp.postgres.database.azure.com";
	DB_PORT: 5432;
	DB_NAME: "postgres";
	DB_PASSWORD: string;
}
